@baseUrl = http://localhost:8000/api
@token = 6|jRBtSutz4Va0DAZYaLVhI0uuR6uBJh9jFZpgimlFc1e3b5ff


### REGISTER USER
POST {{baseUrl}}/register
Content-Type: application/json
Accept: application/json

{
  "name": "Makari",
  "username": "makari",
  "email": "makari@example.com",
  "password": "secret123",
  "password_confirmation": "secret123"
}

###

### LOGIN USER
POST {{baseUrl}}/login
Content-Type: application/json
Accept: application/json

{
  "email": "makari@example.com",
  "password": "secret123"
}

###

### LOGOUT USER
POST {{baseUrl}}/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###

### GET AUTH USER (optional)
GET {{baseUrl}}/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


/* ===========================
   📰 POST ROUTES
   =========================== */

### GET all posts
GET {{baseUrl}}/posts
Accept: application/json

### GET single post
GET {{baseUrl}}/posts/20
Accept: application/json

### CREATE new post
POST {{baseUrl}}/posts
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Belajar Laravel Sanctum Ini contoh aja sih",
  "excerpt": "Panduan singkat membuat API auth dengan Laravel Sanctum updated ehe",
  "content": "Ini isi lengkap postingannya... lagi",
  "status": "draft"
}

### Create new post with image
### ini gak bisa karena entahlah, tapi kalau pake postman bisa kok.
POST {{baseUrl}}/posts
Authorization: Bearer {{token}}
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="title"

Judul Post Contoh Updated
--boundary
Content-Disposition: form-data; name="excerpt"

Ini contoh excerpt
--boundary
Content-Disposition: form-data; name="content"

Ini adalah isi postingan dengan gambar.
--boundary
Content-Disposition: form-data; name="featured_image"; filename="logo.png"
Content-Type: image/png

< ./C:/Users/mmaruf23/Pictures/logo.png
--boundary--

### GET GAMBAR
GET http://localhost:8000/storage/posts/contoh-judul-postingan-nambah-lagi.png

### UPDATE post
PUT {{baseUrl}}/posts/1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Test update gagal policy"
}

### DELETE post
DELETE {{baseUrl}}/posts/21
Accept: application/json
Authorization: Bearer {{token}}
